### ISSUE TITLE
Fails by simply dumping the script

### ISSUE THREAD

**Issue by gajus** [MansaGroup/gcs-cache-action#30]
Here is how we have it setup:

```yaml
- uses: actions/setup-node@v2
  with:
    node-version: '16'
- name: Cache node_modules
  id: node-modules-cache
  uses: mansagroup/gcs-cache-action@v1.0.2
  with:
    bucket: github-action-runner-cache
    path: node_modules
    key: node_modules-${{ hashFiles('**/yarn.lock') }}
    restore-keys: node_modules-${{ hashFiles('**/yarn.lock') }}
```

Here is how it fails:

<img width="1703" alt="Screen Shot 2022-03-08 at 7 30 55 PM" src="https://user-images.githubusercontent.com/973543/157354755-6c15c7cb-cabb-49f3-a68c-21f37f9b5314.png">
